name: "Tests Manuales - Feature Actions"

on:
  workflow_dispatch:
    inputs:
      servicios:
        description: "Nombre del servicio"
        required: true
        default: "AuthService"

jobs:
  pruebas-en-rama:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Test
        run: npx jest ${{ github.event.inputs.servicios }}